# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: WØUNC
email: club@w0unc.org
description: >- # this means to ignore newlines until "baseurl:"
  The Amateur Radio Club of UNC Charlotte is a student interest group whose purposes are to educate
  students, faculty, and staff in becoming licensed amateur radio operators, to foster fellowship
  among amateur radio enthusiasts, and to provide the local community with emergency communications.
  This is a registered student organization on the campus of UNC Charlotte.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: w0unc
ninerengage: https://ninerengage.uncc.edu/organization/amateur-radio-club
code-plugs: https://github.com/w0unc/w0unc-codeplugs
arrl-band-chart: https://arrl.org/files/file/Regulatory/Band%20Chart/Band%20Chart%208_5%20X%2011%20Color.pdf
future: true
collections:
  projects:
    output: true
    permalink: /projects/:path/
    sort_by: progress
  wikis:
    output: true
    permalink: /wikis/:path/
    sort_by: order
  maps:
    output: false
    sort_by: order

# Build settings
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
